### ISSUE TITLE
Context Help needed

### ISSUE THREAD

**Issue by pollockm** [LabVIEW-DCAF/Table-API#19]
The items on the DCAF Table Manager palette lack context help.  Since we expect this API to be one of the most heavily used (and thus have a high support burden), we need to document this API very clearly.

The expected behavior of the Init vi in particular is not clear.
Init: mark the required inputs as required.   
Init: References in (what references?  is there a better name for these?)
Init: object refs (what objects?  is there a better name for these?)
Init: Array (array of what?  Would 'Columns' be a better name?)

Init: capitalization of terminals: pick one.  this one VI has all words capped (Menu Items), first word capped (References in) and no words capped (object refs).  Please pick one.

Listbox create: Add required inputs.  If Top VI is not required, then the function needs to default to the reference of its direct caller. 

Define String Column: Has the description of the Mapping column in context help
Define String Column: What inputs are required?
Define Enum Column: Has the description of the Mapping column in context help
Define Enum Column: What inputs are required?
Define Mapping Column: What inputs are required?

General: make the name of the reference terminal consistent across implementations.  Listbox create outputs a blue 'reference out' wire.  Init expects a red 'Table Manager in' wire - a user might not realize the two are compatible.  I expect 'foo out' and 'foo in', for whatever value of 'foo' you like.

**Comment by becega** [comment]
Everything except General: make the name of the reference terminal consistent across implementations. Listbox create outputs a blue 'reference out' wire. Init expects a red 'Table Manager in' wire - a user might not realize the two are compatible. I expect 'foo out' and 'foo in', for whatever value of 'foo' you like.
The 2 wires are ebacuse the init is the parent class and the List box is a child. when we had datagrid it made sense. We might just make both wires the same color.
