### ISSUE TITLE
Define mapping column: Why do we have a name dependency input?

### ISSUE THREAD

**Issue by pollockm** [LabVIEW-DCAF/Table-API#22]
Weren't we going to use the row header for this purpose?

If the first column is not a name, wouldn't the default of 0 break?

**Comment by becega** [comment]
The default should be -1 but still in some cases you want the name dependency. For example if you want to change the name of the channel that is why it could be on Column 0, like with tagselect module

**Comment by becega** [comment]
closed this in 37c7ae7
