### ISSUE TITLE
Table callbacks - how do they get row header info?

### ISSUE THREAD

**Issue by pollockm** [LabVIEW-DCAF/Table-API#25]
We added row headers to contain the unique ID.  Yay.

How is that information passed to the callbacks?

**Comment by becega** [comment]
WE need to talk about this one in more detail

**Comment by becega** [comment]
Issue moved to [LabVIEW-DCAF/TagEditorCore #317](https://github.com/LabVIEW-DCAF/TagEditorCore/issues/317) via [**ZenHub**](https://www.zenhub.com/)
