### ISSUE TITLE
Multi Column Listbox.lvclass Left Click Issue on Read Only shouldn't discard.

### ISSUE THREAD

**Issue by mcornwall** [LabVIEW-DCAF/Table-API#44]
The Multi Column Listbox.lvclass:Left Click.vi will discard the click if read only is selected. This results in being unable to select different rows on the table by clicking on a read only item. I would expect read only to not pop-up the edit dialog, and instead, allow the user to select rows on the table.

**Comment by becega** [comment]
Duplicated with issue #275 in tag editor core. Table API is now part of core and the bugs are being managed there. We already have a fix for this and will be out in the next release
https://github.com/LabVIEW-DCAF/TagEditorCore/issues/275
